### ISSUE TITLE
Guide on how to generate the onlyfans.json rules? 

### ISSUE THREAD

**Issue by WilliamBlais** [DATAHOARDERS/dynamic-rules#19]
Hi,

I would like to build a tool to automatically extract the rules from the OF website. Is there a guide somewhere that explains how to get the correct values?

Thanks!

**Comment by OFfriend** [comment]
There are no guides. There are already automatic tools. But the tools are private at the moment.

**Comment by Numenorean** [comment]
> There are no guides. There are already automatic tools. But the tools are private ~at the moment.~

i'm interested in these tools. Could you leave your telegram or discord if doesn't use a first one

**Comment by OFfriend** [comment]
> 
> 
> > There are no guides. There are already automatic tools. But the tools are private ~at the moment.~
> 
> i'm interested in these tools. Could you leave your telegram or discord if doesn't use a first one

Maybe I will publish the tools when Onlyfans changes the method.
