### ISSUE TITLE
checksum_indexes

### ISSUE THREAD

**Issue by w-a-n-g-s-h-u-n** [DATAHOARDERS/dynamic-rules#239]
``

**Comment by OFfriend** [comment]
yes but that's only one step

**Comment by OFfriend** [comment]
yes but that's only one step. If you have figured out how it works, it would be good if you keep it secret.

**Comment by w-a-n-g-s-h-u-n** [comment]
> yes but that's only one step. If you have figured out how it works, it would be good if you keep it secret.

ok
Thank you for your contribution
