### ISSUE TITLE
onlyfans.json is broken/wrong/empty

### ISSUE THREAD

**Issue by coltonshipley** [DATAHOARDERS/dynamic-rules#241]
The dynamic rules file was updated with no contents.

**Comment by oftrash** [comment]
@DIGITALCRIMINAL / @DIGITALCRIMINALS

Somethings up with @OFfriend  / @hippothon  tool

**Comment by oftrash** [comment]
FYI the old hash values in 6bf2bc6d1e6fb5ad975d5110fad6bf1c79d16e7f still do work for now

https://github.com/DATAHOARDERS/dynamic-rules/blob/6bf2bc6d1e6fb5ad975d5110fad6bf1c79d16e7f/onlyfans.json

**Comment by DIGITALCRIMINALS** [comment]
Damn, I am not looking forward to decoding the algorithm again since I lost my python script that did it...

You can paste that link into the config where it says dynamic rules link to get it working again.

**Comment by OFfriend** [comment]
I fixed it. Sorry!  I have add more checks

**Comment by OFfriend** [comment]
Okay `JSON.stringify` failed an created an empty `onlyfans.json`. I added checks to never commit and push broken/empty `onlyfans.json`

**Comment by OFfriend** [comment]
Okay `JSON.stringify` failed and created an empty `onlyfans.json`. I added checks to never commit and push broken/empty `onlyfans.json` again
