### ISSUE TITLE
No longer automated rules

### ISSUE THREAD

**Issue by OFfriend** [DATAHOARDERS/dynamic-rules#245]
My IPs got blocked and i can't longer provide dynamic rules

**Comment by OFfriend** [comment]
it's related to https://github.com/DIGITALCRIMINALS/OnlyFans/issues/695

**Comment by OFfriend** [comment]
Of course I can't use my real IP Address.

**Comment by RedMethylamine** [comment]
Hello,

I'm interested in continuing to do the work you've been doing so far, but I always get stuck with the Javascript. Would you be willing to share your tools or the process to break the auth?

I still have access with my IPs and proxies and with your help maybe I can keep updating the rules.

**Comment by OFfriend** [comment]
I'll think about it. But there are other people who already know how to do it.

**Comment by RedMethylamine** [comment]
Thanks, I appreciate it. Could you please point me in the right direction to talk to these people?

**Comment by OFfriend** [comment]
new location: https://github.com/DIGITALCRIMINALS/dynamic-rules
