### ISSUE TITLE
sign 17 not fully working 

### ISSUE THREAD

**Issue by oftrash** [DATAHOARDERS/dynamic-rules#5]
not sure if 17 fully works

**Comment by iamnotdev** [comment]
yes, it isn't working

**Comment by oftrash** [comment]
@hippothon / @DIGITALCRIMINAL checking in if 17 was put in incorrectly?

**Comment by DIGITALCRIMINAL** [comment]
I'm aware, I calculated it wrong, but I know what is wrong. Its just the 3 digit sum that's incorrect

**Comment by oftrash** [comment]
Ok cool thanks

**Comment by iamnotdev** [comment]
it's already 19

**Comment by DIGITALCRIMINAL** [comment]
Sign 17 working now, I had to build a whole new tool on my end and I'm very happy with it :)

The more they changed, the more I figure out tbh.

**Comment by OFfriend** [comment]
Im working on an automated way to extract static_param, format, checksum_indexes and checksum_constant. Everything is ready except for the checksum_constant.

**Comment by iamnotdev** [comment]
> Sign 17 working now, I had to build a whole new tool on my end and I'm very happy with it :)
> 
> The more they change, the more I figure out tbh.

Thank you!
